#ifndef PREFERENCES_GLOBAL_H
#define PREFERENCES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PREFERENCES_LIBRARY)
#  define PREFERENCESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PREFERENCESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PREFERENCES_GLOBAL_H
